title: Placeholderview
description: Simple, Easy and Superfast dynamic view List creation with Awesome animations prebuilt!
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
